from .vector_api import IngestBody, ingest_chunks
from .pdf.parser import parse, chunks_to_json
from fastapi import APIRouter, File, Form, UploadFile, HTTPException
from tempfile import NamedTemporaryFile
from PyPDF2 import PdfReader
from supabase import create_client, Client
import os

router = APIRouter(prefix="/chunk", tags=["chunk"])

# ✅ Initialize Supabase client
SUPABASE_URL = os.getenv("SUPABASE_URL")
SUPABASE_KEY = os.getenv("SUPABASE_SERVICE_ROLE_KEY")  # Use service role key, not anon
supabase: Client = create_client(SUPABASE_URL, SUPABASE_KEY)


@router.post("/upload-pdf")
async def upload_pdf(file: UploadFile = File(...)):
    temp_file = None
    try:
        # 1️⃣ Insert placeholder record into Supabase
        filename = file.filename
        insert_data = {
            "name": filename,
            "qdrant_doc_id": "temp",
            "overall_score": 0,
            "status": "0",
            "num_pages": 0
        }

        insert_response = supabase.table("RFPs").insert(insert_data).execute()
        if not insert_response.data:
            raise HTTPException(status_code=500, detail="Failed to insert Supabase record")

        row = insert_response.data[0]
        id_ = row["id"]  # UUID generated by Supabase
        qdrant_doc_id = id_

        # 2️⃣ Update qdrant_doc_id in Supabase
        supabase.table("RFPs").update({"qdrant_doc_id": qdrant_doc_id}).eq("id", id_).execute()

        # 3️⃣ Save PDF temporarily
        temp_file = NamedTemporaryFile(suffix=".pdf")
        temp_file.write(await file.read())
        temp_path = temp_file.name

        # 4️⃣ Count actual pages using PyPDF2
        reader = PdfReader(temp_path)
        num_pages = len(reader.pages)

        # 5️⃣ Parse and chunk PDF
        chunks = parse(temp_path)
        json_chunks = chunks_to_json(qdrant_doc_id, chunks)["chunks"]

        # 6️⃣ Ingest into Qdrant
        ingest_body = IngestBody(doc_id=qdrant_doc_id, chunks=json_chunks)
        qdrant_result = ingest_chunks(ingest_body)

        # 7️⃣ Update Supabase with page count
        supabase.table("RFPs").update({
            "num_pages": num_pages
        }).eq("id", id_).execute()

        # 8️⃣ Prepare return result
        result = {
            "id": id_,
            "qdrant_doc_id": qdrant_doc_id,
            "name": filename,
            "overall_score": 0,
            "status": "0",
            "num_pages": num_pages,
            "qdrant_result": qdrant_result,
        }

    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))

    finally:
        if temp_file:
            temp_file.close()
        return result
