// src/api/uploadPDF.js
import { createClient } from "@supabase/supabase-js";

// Initialize Supabase client
const supabaseUrl = process.env.REACT_APP_SUPABASE_URL;
const supabaseKey = process.env.REACT_APP_SUPABASE_ANON_KEY;
const supabase = createClient(supabaseUrl, supabaseKey);

/**
 * Upload a PDF, insert into Supabase, and ingest into Qdrant
 * @param {File} file - PDF file
 */
export async function uploadPDF(file) {
  if (!file) throw new Error("No file provided");

  const filename = file.name;

  try {
    // 1️⃣ Insert row into Supabase with default values
    const { data, error } = await supabase
      .from("RFPs")
      .insert([{
        name: filename,
        qdrant_doc_id: "temp", // temporary placeholder
        overall_score: 0,
        status: "0",
        num_pages: 0
      }])
      .select()
      .single();

    if (error) {
      console.error("Supabase insert error:", error);
      throw error;
    }

    // 2️⃣ Use autogenerated id as qdrant_doc_id
    const id = data.id;
    const qdrant_doc_id = String(id);

    // Update the Supabase row with proper qdrant_doc_id
    const { error: updateError } = await supabase
      .from("RFPs")
      .update({ qdrant_doc_id })
      .eq("id", id);

    if (updateError) {
      console.error("Supabase update error:", updateError);
      throw updateError;
    }

    console.log("Supabase row created:");
    console.log({ id, qdrant_doc_id, name: filename, overall_score: 0, status: "0", num_pages: 0 });

    // 3️⃣ Send PDF to FastAPI for Qdrant ingestion
    const formData = new FormData();
    formData.append("file", file);
    formData.append("doc_id", qdrant_doc_id); // match Supabase id

    const response = await fetch("http://localhost:8080/chunk/upload-pdf", {
      method: "POST",
      body: formData,
    });
    console.log("done");
    
    if (!response.ok) {
      const errText = await response.text();
      throw new Error(`Qdrant upload failed: ${response.status} ${errText}`);
    }

    const result = await response.json();
    console.log("Qdrant ingestion result:", result);

    return { 
      id, 
      qdrant_doc_id, 
      name: filename, 
      overall_score: 0, 
      status: "0", 
      num_pages: 0,
      qdrant_result: result
    };

  } catch (err) {
    console.error("Error uploading PDF:", err);
    throw err;
  }
}
