// src/api/uploadPDF.js
import { createClient } from "@supabase/supabase-js";

// Initialize Supabase client
const supabaseUrl = process.env.REACT_APP_SUPABASE_URL;
const supabaseKey = process.env.REACT_APP_SUPABASE_ANON_KEY;
const supabase = createClient(supabaseUrl, supabaseKey);

/**
 * Upload a PDF to Supabase and set default values
 * @param {File} file - PDF file
 */
export async function uploadPDF(file) {
  if (!file) throw new Error("No file provided");

  const filename = file.name;

  try {
    // Insert row into Supabase with default values
    const { data, error } = await supabase
      .from("RFPs")
      .insert([{
        name: filename,
        qdrant_doc_id: "temp",    // placeholder, will replace with id
        overall_score: 0,
        status: "0",               // assuming status is text
        num_pages: 0
      }])
      .select()
      .single();

    if (error) {
      console.error("Supabase insert error:", JSON.stringify(error, null, 2));
      throw error;
    }

    // Use the autogenerated id as qdrant_doc_id
    const id = data.id;
    const qdrant_doc_id = String(id);

    // Update the row to set correct qdrant_doc_id
    await supabase
      .from("RFPs")
      .update({ qdrant_doc_id })
      .eq("id", id);

    // Log the values
    console.log("PDF uploaded successfully:");
    console.log("id:", id);
    console.log("qdrant_doc_id (string):", qdrant_doc_id);
    console.log("name:", filename);
    console.log("overall_score: 0, status: '0', num_pages: 0");

    return { id, qdrant_doc_id, name: filename, overall_score: 0, status: "0", num_pages: 0 };
  } catch (err) {
    console.error("Error uploading PDF:", err);
    throw err;
  }
}
